enroll/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='first'),
    path('terms', views.terms, name='terms'),
    path('enrol_form', views.enrol, name='enrol_form'),
    path('register', views.register, name='register'),
    path('ajax/load-states/', views.load_stats, name='ajax_load_states'),
    path('ajax/load-lgas/', views.load_lga, name='ajax_load_lgas'),
    path('ajax/load-towns/', views.load_town, name='ajax_load_towns'),
    path('capture', views.capture, name='capture'),
    path('informal', views.informal, name='informal')
]

registeration/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('enroll.urls'))
]

enroll/models.py
from django.db import models


# Create your models here.


class First(models.Model):
    choices = (
        ('1', 'Formal (Public Sector)'),
        ('2', 'Informal (Private Sector)'),
    )
    plan_type = models.CharField(max_length=30, blank=False, null=False, choices=choices)

    def __str__(self):
        return self.plan_type


class Terms(models.Model):
    term = models.BooleanField()


class Enroll(models.Model):
    choices = (
        ('1', 'Grace Hospital'),
        ('2', 'Gifted Hospice'),
        ('3', 'Tranquil Hospital'),
    )
    mda_type = models.CharField(max_length=30, blank=True, null=True, choices=choices)
    employment_number = models.CharField(max_length=50, blank=True, null=True)
    nin = models.CharField(max_length=50, blank=True, null=True)


class Country(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class State(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Lga(models.Model):
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Town(models.Model):
    lga = models.ForeignKey(Lga, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Registration(models.Model):
    sex = (
        ('1', 'Male'),
        ('2', 'Female'),
        ('3', 'Rather not say'),
    )
    group = (
        ('1', 'A'),
        ('2', 'B'),
        ('3', 'AB'),
        ('4', 'O'),
    )
    kin = (
        ('1', 'Cousin'),
        ('2', 'Nephew'),
        ('3', 'other')
    )
    plan = (
        ('1', 'Public Sector Plan'),
        ('2', 'Public Sector Plan')
    )
    school = (
        ('1', 'University of Ibadan College of Medicine'),
        ('2', 'Obafemi Awolowo University'),
        ('3', 'Ahmadu Bello University Faculty of Medicine'),
        ('4', 'University of Lagos College of Medicine'),
        ('5', 'Lagos State University College of Medicine'),
        ('6', 'Nsukka Faculty of Medical Sciences'),
        ('7', 'University of Ilorin College of Health Sciences'),
        ('8', 'Delta State University'),
        ('9', ' Niger Delta University College of Health Sciences'),
        ('10', 'Imo State University Faculty of Medicine'),
    )
    genotypes = (
        ('1', 'AA'),
        ('2', 'AO'),
        ('3', 'BB'),
        ('4', 'BO'),
        ('5', 'AB'),
        ('6', 'OO')
    )
    religions = (
        ('1', 'Christian'),
        ('2', 'Muslim'),
        ('3', 'other')
    )
    status = (
        ('1', 'Single'),
        ('2', 'Married')
    )
    dependants = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
    )
    hcp_lga = (
        ('1', 'Ajeromi-Ifelodun'),
        ('2', 'Abuja Municipal Area Council	'),
        ('3', 'Aguata'),
        ('4', 'Awgu'),
    )
    hcp = (
        ('1', 'Sancta Maria Specialist & Mat.'),
        ('2', 'Abia State University Teaching Hospital'),
        ('3', 'Federal Medical Centre, Umuahia'),
        ('4', 'Life Care Clinics Ltd'),
    )
    spouse_sex = (
        ('1', 'Male'),
        ('2', 'Female'),
        ('3', 'Rather not say'),
    )
    spouse_group = (
        ('1', 'A'),
        ('2', 'B'),
        ('3', 'AB'),
        ('4', 'O'),
    )
    diabetic = (
        ('1', 'type 1'),
        ('2', 'type 2'),
        ('3', 'Gestational'),
        ('4', 'None'),
    )
    hyper = (
        ('1', 'Primary'),
        ('2', 'Secondary'),
        ('3', 'None'),
    )
    sickle = (
        ('1', 'Sickle Cell Anemia (SS)'),
        ('2', 'Sickle Hemoglobin-C Disease (SC)'),
        ('3', 'Sickle Beta-Plus Thalassemia'),
        ('4', 'Sickle Beta-Zero Thalassemia'),
        ('5', 'None'),
    )
    cancer_type = (
        ('1', 'Carcinoma'),
        ('2', 'Sarcoma'),
        ('3', 'Leukemia'),
        ('4', 'Lymphoma'),
        ('5', 'None'),
    )
    kidneys = (
        ('1', 'Kidney Stones'),
        ('2', 'Chronic Kidney Disease'),
        ('3', 'Urinary tract infections'),
        ('4', 'Glomerulonephritis'),
        ('5', 'None'),
    )
    name = models.CharField(max_length=150, blank=True, null=True)
    title = models.CharField(max_length=50, blank=True, null=True)
    surname = models.CharField(max_length=50, blank=True, null=True)
    first_name = models.CharField(max_length=50, blank=True, null=True)
    middle_name = models.CharField(max_length=50, blank=True, null=True)
    gender = models.CharField(max_length=30, blank=True, null=True, choices=sex)
    mobile_number = models.CharField(max_length=50, blank=True, null=True)
    email = models.EmailField(max_length=254, blank=True, null=True)
    date_of_birth = models.DateTimeField(auto_now_add=False, auto_now=False, blank=True, null=True)
    address = models.CharField(max_length=50, blank=True, null=True)
    blood_group = models.CharField(max_length=30, blank=True, null=True, choices=group)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, blank=True, null=True)
    state = models.ForeignKey(State, on_delete=models.SET_NULL, blank=True, null=True)
    lga = models.ForeignKey(Lga, on_delete=models.SET_NULL, blank=True, null=True)
    town = models.ForeignKey(Town, on_delete=models.SET_NULL, blank=True, null=True)
    next_of_kin = models.CharField(max_length=50, blank=True, null=True)
    next_of_kin_address = models.CharField(max_length=50, blank=True, null=True)
    next_of_kin_phone_no = models.CharField(max_length=50, blank=True, null=True)
    relationship_with_kin = models.CharField(max_length=50, blank=True, null=True, choices=kin)
    choose_plan = models.CharField(max_length=50, blank=True, null=True, choices=plan)
    school_name = models.CharField(max_length=50, blank=True, null=True, choices=school)
    genotype = models.CharField(max_length=30, blank=True, null=True, choices=genotypes)
    religion = models.CharField(max_length=50, blank=True, null=True, choices=religions)
    marital_status = models.CharField(max_length=50, blank=True, null=True, choices=status)
    no_of_dependants = models.CharField(max_length=50, blank=True, null=True, choices=dependants)
    preferred_primary_hcp_lga = models.CharField(max_length=50, blank=True, null=True, choices=hcp_lga)
    preferred_primary_hcp = models.CharField(max_length=50, blank=True, null=True, choices=hcp)
    date_of_employment = models.DateTimeField(auto_now_add=False, auto_now=False, blank=True, null=True)
    spouse_name = models.CharField(max_length=50, blank=True, null=True)
    spouse_dob = models.DateTimeField(auto_now_add=False, auto_now=False, blank=True, null=True)
    spouse_sex = models.CharField(max_length=50, blank=True, null=True, choices=spouse_sex)
    spouse_blood_group = models.CharField(max_length=50, blank=True, null=True, choices=spouse_group)
    spouse_image = models.ImageField(upload_to='images', null=True, blank=True)
    child_name = models.CharField(max_length=50, blank=True, null=True)
    child_dob = models.DateTimeField(auto_now_add=False, auto_now=False, blank=True, null=True)
    child_gender = models.CharField(max_length=50, blank=True, null=True, choices=sex)
    child_blood_group = models.CharField(max_length=50, blank=True, null=True, choices=group)
    child_image = models.ImageField(upload_to='images', null=True, blank=True)
    principal_category = models.CharField(max_length=50, blank=True, null=True, choices=kin)
    diabetes = models.CharField(max_length=50, blank=True, null=True, choices=diabetic)
    hypertension = models.CharField(max_length=50, blank=True, null=True, choices=hyper)
    sickle_cell = models.CharField(max_length=50, blank=True, null=True, choices=sickle)
    cancer = models.CharField(max_length=50, blank=True, null=True, choices=cancer_type)
    kidney_issue = models.CharField(max_length=50, blank=True, null=True, choices=kidneys)

    def __str__(self):
        return str(self.surname)


class Capture(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)


class Informal(models.Model):
    new_choices = (
        ('1', 'Domain Hospital'),
        ('2', 'Western Hospice'),
        ('3', 'Daniel Hospital'),
    )
    mda_name = models.CharField(max_length=30, blank=True, null=True, choices=new_choices)
    employment_id = models.CharField(max_length=50, blank=True, null=True)
    nim = models.CharField(max_length=50, blank=True, null=True)

enroll/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import *


# Create your views here.


def index(request):
    form = PlanForm
    if request.method == 'POST':
        form = PlanForm(request.POST)
        plan = request.POST['plan_type']
        if form.is_valid():
            # return redirect('/terms')
            if plan == str(1):
                return redirect('/terms')
            if plan == str(2):
                return redirect('/informal')

    context = {'form': form}
    return render(request, 'first.html', context)


def terms(request):
    form = CheckBox
    if request.method == 'POST':
        form = CheckBox(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/enrol_form')
    context = {'form': form}
    return render(request, 'terms.html', context)


def enrol(request):
    third = Enroll.objects.all()
    form = EnrolForm
    if request.method == 'POST':
        form = EnrolForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('register')
    context = {'form': form, 'third': third}
    return render(request, 'enrol_form.html', context)


def register(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('capture')
    context = {'form': form}
    return render(request, 'register.html', context)


def load_stats(request):
    country_idm = request.GET.get('country_id')
    states = State.objects.filter(country_id=country_idm)
    context = {'states': states}
    return render(request, 'state_dropdown_list_options.html', context)


def load_lga(request):
    state_main_id = request.GET.get('state_id')
    lgas = Lga.objects.filter(state_id=state_main_id)
    context = {'lgas': lgas}
    return render(request, 'lga_dropdown_list_options.html', context)


def load_town(request):
    lga_main_id = request.GET.get('lga_id')
    towns = Town.objects.filter(lga_id=lga_main_id)
    context = {'towns': towns}
    return render(request, 'town_dropdown_list_options.html', context)


def capture(request):
    method = Capture.objects.all()
    form = CaptureForm
    if request.method == 'POST':
        form = CaptureForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Registration Successful!')
            return redirect('/')
    context = {'form': form, 'method': method}
    return render(request, 'bio.html', context)


def informal(request):
    inform = Informal.objects.all()
    form = InFormalForm
    if request.method == 'POST':
        form = InFormalForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('register')
    context = {'form': form, 'inform': inform}
    return render(request, 'informal.html', context)

enroll/templates/bio.html
{% include 'headers.html' %}
{% load crispy_forms_tags %}
{% load static %}

<div class="nk-content ">
    <div class="container-fluid">


<div class="card">
    <div class="card-body">
              <form method="POST" action="">
                      {% csrf_token %}
                         {{form | crispy}}

                  <button id="pop" type="submit" class="btn btn-primary">Click For Biometrics</button>
                    </form>
    </div>
</div>
    </div>
</div>

{% include 'footers.html' %}

enroll/templates/enrol_form.html
{% include 'headers.html' %}
{% load crispy_forms_tags %}
{% load static %}

<div class="nk-content ">
    <div class="container-fluid">


<div class="card">
    <div class="card-body">
              <form method="POST" action="">
                      {% csrf_token %}
                         {{form | crispy}}

                  <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
    </div>
</div>
    </div>
</div>


{% include 'footers.html' %}

enroll/templates/first.html
{% include 'headers.html' %}
{% load crispy_forms_tags %}
{% load static %}

<div class="nk-content ">
    <div class="container-fluid">


<div class="card">
    <div class="card-body">
              <form method="POST" action="">
                      {% csrf_token %}
                         {{form | crispy}}

                  <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
    </div>
</div>
    </div>
</div>

{% include 'footers.html' %}
   <script src="{% static 'js/sweetalert2.all.min.js' %}"></script>
{% for message in messages %}
    <script>
       Swal.fire({
  position: 'center',
  icon: 'success',
  title: '{{message}}',
  showConfirmButton: true,
  timer: 15000
})
{% endfor %}
    </script>

enroll/templates/footers.html
{% load static %}
 <!-- footer @s -->
                <div class="nk-footer">
                    <div class="container-fluid">
                        <div class="nk-footer-wrap">
                            <div class="nk-footer-copyright"> &copy; 2021 Registration Process by <a href="javascript:void" >Donald Nwokoro</a>
                            </div>
                            <div class="nk-footer-links">
                                <ul class="nav nav-sm">
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- footer @e -->
 </div>
</div>
        <!-- main @e -->
    </div>
<!-- JavaScript -->
    <script src="{% static 'js/bundle.js' %}"></script>
<!--  <script src="{% static 'js/scrumboard.js' %}"></script>-->

    <script src="{% static 'js/sweetalert2.all.min.js' %}"></script>

 <script src="{% static 'js/all.js' %}"></script>
   <script src="{% static 'js/jquery-ui-1.12.1/jquery-ui.js' %}"></script>
    <script>
$(document).ready(function(){
              $(".datetimeinput").datepicker({changeYear: true,changeMonth: true, dateFormat: 'yy-mm-dd'});
});
    </script>

<script>
       var CurURL = window.location.href, urlSplit = CurURL.split("#");
	var $nav_link = $(".nk-menu-link, .menu-link, .nav-link");
	if ($nav_link.length > 0) {
		$nav_link.each(function() {
			if (CurURL === (this.href) && (urlSplit[1]!=="")) {
				$(this).closest("li").addClass("active").parent().closest("li").addClass("active");
			}
		});
	}
    </script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/charts/chart-ecommerce.js' %}"></script>

</body>

</html>

enroll/templates/headers.html
<!DOCTYPE html>
{% load static %}
<html lang="en" class="js">

<head>
    <base href="../">
    <meta charset="utf-8">
    <meta name="author" content="Softnio">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A powerful and conceptual apps base dashboard template that especially build for developers and programmers.">
    <!-- Fav Icon  -->
    <link rel="shortcut icon" href="./images/favicon.png">
    <!-- Page Title  -->
    <title></title>
    <!-- StyleSheets  -->
    <link rel="stylesheet" href="{% static 'css/dashlite.css' %}">
    <link id="skin-default" rel="stylesheet" href="{% static 'css/theme.css' %}">
    <link href="{% static 'js/jquery-ui-1.12.1/jquery-ui.min.css' %}" rel="stylesheet">
    <link href="{% static 'js/jquery-ui-1.12.1/jquery-ui.structure.min.css' %}" rel="stylesheet">
    <link href="{% static 'js/jquery-ui-1.12.1/jquery-ui.theme.min.css' %}" rel="stylesheet">
     <link href="{% static 'css/all.css' %}" rel="stylesheet">
    <link href="{% static 'css/sweetalert2.min.css' %}" rel="stylesheet">
     <link href="{% static 'css/navbar-top-fixed.css' %}" rel="stylesheet">
</head>
<body class="nk-body light-mode npc-default has-sidebar ">
 <div class="nk-app-root">
        <!-- main @s -->
        <div class="nk-main ">
             <!-- sidebar @s -->
            <div class="nk-sidebar nk-sidebar-fixed is-light " data-content="sidebarMenu">
                <div class="nk-sidebar-element nk-sidebar-head">
                    <div class="nk-sidebar-brand">
                        <a href="/" class="logo-link nk-sidebar-logo">
                            <img class="logo-light logo-img" src="{% static 'images/logo.png' %}" srcset="./images/logo2x.png 2x" alt="logo">
                            <img class="logo-dark logo-img" src="{% static 'images/logo-dark.png' %}" srcset="./images/logo-dark2x.png 2x" alt="logo-dark">
                            <img class="logo-small logo-img logo-img-small" src="{% static 'images/logo-small.png' %}" srcset="./images/logo-small2x.png 2x" alt="logo-small">
                        </a>
                    </div>
                    <div class="nk-menu-trigger mr-n2">
                        <a href="#" class="nk-nav-toggle nk-quick-nav-icon d-xl-none" data-target="sidebarMenu"><em class="icon ni ni-arrow-left"></em></a>
                        <a href="#" class="nk-nav-compact nk-quick-nav-icon d-none d-xl-inline-flex" data-target="sidebarMenu"><em class="icon ni ni-menu"></em></a>
                    </div>
                </div><!-- .nk-sidebar-element -->
                <div class="nk-sidebar-element">
                    <div class="nk-sidebar-content">
                        <div class="nk-sidebar-menu" data-simplebar>
                            <ul class="nk-menu">

                                <li class="nk-menu-heading">
                                    <h6 class="overline-title text-primary-alt">Navigation</h6>
                                </li><!-- .nk-menu-item -->
                                  <li class="nk-menu-item">
                                    <a href="/" class="nk-menu-link">
                                        <span class="nk-menu-icon"><em class="icon ni ni-home-fill"></em></span>
                                        <span class="nk-menu-text">Home</span>
                                    </a>
                                </li><!-- .nk-menu-item -->

                            </ul><!-- .nk-menu -->
                        </div><!-- .nk-sidebar-menu -->
                    </div><!-- .nk-sidebar-content -->
                </div><!-- .nk-sidebar-element -->
            </div>
            <!-- sidebar @e -->
            <!-- wrap @s -->
            <div class="nk-wrap ">
                <!-- main header @s -->
                <div class="nk-header nk-header-fixed is-light">
                    <div class="container-fluid">
                        <div class="nk-header-wrap">
                            <div class="nk-menu-trigger d-xl-none ml-n1">
                                <a href="#" class="nk-nav-toggle nk-quick-nav-icon" data-target="sidebarMenu"><em class="icon ni ni-menu"></em></a>
                            </div>
                            <div class="nk-header-brand d-xl-none">
                                <a href="/" class="logo-link">
                                    <img class="logo-light logo-img" src="{% static 'images/logo.png' %}" srcset="./images/logo2x.png 2x" alt="logo">
                                    <img class="logo-dark logo-img" src="{% static 'images/logo-dark.png' %}" srcset="./images/logo-dark2x.png 2x" alt="logo-dark">
                                </a>
                            </div><!-- .nk-header-brand -->
                            <div class="nk-header-search ml-3 ml-xl-0">
                                <em class="icon ni ni-search"></em>
                                <input type="text" class="form-control border-transparent form-focus-none" placeholder="Search anything">
                            </div><!-- .nk-header-news -->
                            <div class="nk-header-tools">
                                <ul class="nk-quick-nav">
                                    <li class="dropdown user-dropdown">
                                        <a href="#" class="dropdown-toggle mr-n1" data-toggle="dropdown">
                                            <div class="user-toggle">
                                                <div class="user-avatar sm">
                                                    <em class="icon ni ni-user-alt"></em>
                                                </div>
                                                <div class="user-info d-none d-xl-block">
                                                    <div class="user-name dropdown-indicator"></div>
                                                </div>
                                            </div>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-md dropdown-menu-right">
                                            <div class="dropdown-inner user-card-wrap bg-lighter d-none d-md-block">
                                                <div class="user-card">
                                                    <div class="user-avatar">
                                                        <span>AB</span>
                                                    </div>
                                                    <div class="user-info">
                                                        <span class="lead-text"></span>
                                                        <span class="sub-text"></span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="dropdown-inner">
                                                <ul class="link-list">
                                                    <li><a class="dark-switch" href="#"><em class="icon ni ni-moon"></em><span>Dark Mode</span></a></li>
                                                </ul>
                                            </div>
                                            <div class="dropdown-inner">
                                                <ul class="link-list">

                                                    <li><a href="/accounts/logout"><em class="icon ni ni-signout"></em><span>Log out</span></a></li>


                                                </ul>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div><!-- .nk-header-wrap -->
                    </div><!-- .container-fliud -->
                </div>
                <!-- main header @e -->
                <!-- content @s -->

                <!-- content @e -->


            <!-- wrap @e -->

enroll/templates/informal.html
{% include 'headers.html' %}
{% load crispy_forms_tags %}
{% load static %}

<div class="nk-content ">
    <div class="container-fluid">


<div class="card">
    <div class="card-body">
              <form method="POST" action="">
                      {% csrf_token %}
                         {{form | crispy}}

                  <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
    </div>
</div>
    </div>
</div>

{% include 'footers.html' %}

enroll/templates/lga_dropdown_list_options.html
<option value="">---------</option>
{% for lga in lgas %}
<option value="{{ lga.pk }}">{{ lga.name }}</option>
{% endfor %}

enroll/templates/register.html
{% include 'headers.html' %}
{% load crispy_forms_tags %}
{% load static %}

<div class="nk-content ">
    <div class="container-fluid">


<div class="card">
    <div class="card-body">
              <form method="POST" action=" " enctype="multipart/form-data" id="personForm" data-towns-url="{% url 'ajax_load_towns' %}">
                      {% csrf_token %}
                         {{form | crispy}}

                  <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
    </div>
</div>
    </div>
</div>

{% include 'footers.html' %}


<script>
    $("#id_country").change(function () {
        const url = $("#personForm").attr("data-towns-url");  // get the url of the `load_cities` view
        const countryId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: '{% url 'ajax_load_states' %}',                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'country_id': countryId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_state").html(data);
                }
        });

    });


     $("#id_state").change(function () {
        const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_lga's` view
        const stateId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: '{% url 'ajax_load_lgas' %}',                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'state_id': stateId       // add the country id to the GET parameters
            },
            success: function (data) {
                $("#id_lga").html(data);
            }
        });

    });

$("#id_lga").change(function () {
        const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_towns` view
        const lga_Id = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: '{% url 'ajax_load_towns' %}',                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'lga_id': lga_Id       // add the country id to the GET parameters
            },
            success: function (data) {
                $("#id_town").html(data);
            }
        });

    });

</script>

enroll/templates/state_dropdown_list_options.html
<option value="">---------</option>
{% for state in states %}
<option value="{{ state.pk }}">{{ state.name }}</option>
{% endfor %}

enroll/templates/terms.html
{% include 'headers.html' %}
{% load crispy_forms_tags %}
{% load static %}

<div class="nk-content ">
    <div class="container-fluid">


<div class="card">
    <div class="card-body">
              <form method="POST" action="">
                      <p>Please read the terms and conditions carefully before registration  {% csrf_token %}
                        {{form | crispy}}
                 I agree to these terms and conditions</p>
                  <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
    </div>
</div>

    </div>
</div>


{% include 'footers.html' %}

enroll/templates/town_dropdown_list_options.html
<option value="">---------</option>
{% for town in towns %}
<option value="{{ town.pk }}">{{ town.name }}</option>
{% endfor %}